"""Add amount to the payment table

Revision ID: 11163521cdbf
Revises: d5fa5536b818
Create Date: 2022-03-22 16:24:58.439562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11163521cdbf'
down_revision = 'd5fa5536b818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    # ### end Alembic commands ###
