"""Turn user id into string

Revision ID: d5fa5536b818
Revises: d9e74ff593f9
Create Date: 2022-03-22 15:53:17.821334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fa5536b818'
down_revision = 'd9e74ff593f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
