"""Change to payment service

Revision ID: d9e74ff593f9
Revises: d3d4af44c161
Create Date: 2022-03-22 15:51:54.569800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e74ff593f9'
down_revision = 'd3d4af44c161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_returns_id', table_name='returns')
    op.drop_table('returns')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_returns_id', 'returns', ['id'], unique=False)
    # ### end Alembic commands ###
